added empty mode (isolated net)
stackhpc/ansible-role-libvirt-host pull request #53
Opened 2022-04-28 13:43 UTC by IncredibleRichie

closes https://github.com/stackhpc/ansible-role-libvirt-host/issues/38

2022-04-29 11:02 UTC, markgoddard requested changes

2022-04-29 11:02 UTC, markgoddard commented on templates/network.xml.j2
> +{% if item.mode is defined %}
I don't think we need this condition - it seems many of these things are still supported: https://libvirt.org/formatnetwork.html#isolated-network-config

2022-04-29 11:23 UTC, IncredibleRichie commented on templates/network.xml.j2
> +{% if item.mode is defined %}
You´re right, i´ve changed it.

2022-05-02 08:26 UTC, IncredibleRichie commented on templates/network.xml.j2
> +  <domain name='{{ item.domain|default(item.name) }}'/>
yes that saves some lines

2022-05-03 08:38 UTC, markgoddard approved these changes
Thanks

2022-05-03 08:38 UTC, merged